export enum Action {
    ELEVATOR_MOVE = 'ELEVATOR_MOVE',
    ELEVATOR_READY = 'ELEVATOR_READY',
    ELEVATOR_REQUESTED_UP = 'ELEVATOR_REQUESTED_UP',
    ELEVATOR_REQUESTED_DOWN = 'ELEVATOR_REQUESTED_DOWN',
    ELEVATOR_BUTTON_PRESSED = 'ELEVATOR_BUTTON_PRESSED'
}
